package com.example.project

import android.annotation.SuppressLint
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.ImageView
import android.widget.TextView

class sanhak_floor7 : AppCompatActivity() {
    @SuppressLint("MissingInflatedId")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_sanhak_floor7)

        var checktime: TextView = findViewById(R.id.text_time37)
        var checkfloor: TextView = findViewById(R.id.text_floor37)

        checktime.text = intent.getStringExtra("time")
        checkfloor.text = intent.getStringExtra("floor")

        var time = intent.getStringExtra("time")
        var iv711: ImageView = findViewById(R.id.imageView711)
        var iv712: ImageView = findViewById(R.id.imageView712)
        var iv713: ImageView = findViewById(R.id.imageView713)
        var iv714: ImageView = findViewById(R.id.imageView714)
        var iv715: ImageView = findViewById(R.id.imageView715)
        var iv717: ImageView = findViewById(R.id.imageView717)
        var iv718: ImageView = findViewById(R.id.imageView718)
        var iv719: ImageView = findViewById(R.id.imageView719)
        var iv720: ImageView = findViewById(R.id.imageView720)

        if (time=="현재시각 : 12시 월요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 월요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 월요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 월요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 화요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 화요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 화요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 수요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 수요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 금요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 금요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 금요일") iv711.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 금요일") iv711.setImageResource(R.drawable.red)
        else iv711.setImageResource(R.drawable.green)

        if (time=="현재시각 : 11시 월요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 월요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 월요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 화요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 화요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 화요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 목요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 목요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 목요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 목요일") iv712.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 17시 목요일") iv712.setImageResource(R.drawable.red)
        else iv712.setImageResource(R.drawable.green)

        if (time=="현재시각 : 10시 월요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 월요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 월요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 화요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 화요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 화요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 수요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 수요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 목요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 목요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 금요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 금요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 금요일") iv713.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 금요일") iv713.setImageResource(R.drawable.red)
        else iv713.setImageResource(R.drawable.green)

        if (time=="현재시각 : 09시 월요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 월요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 월요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 월요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 화요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 화요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 화요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 수요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 수요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 목요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 목요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 목요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 목요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 금요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 금요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 금요일") iv714.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 금요일") iv714.setImageResource(R.drawable.red)
        else iv714.setImageResource(R.drawable.green)

        if (time=="현재시각 : 10시 화요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 화요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 화요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 화요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 수요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 수요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 수요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 수요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 수요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 목요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 목요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 목요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 목요일") iv715.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 목요일") iv715.setImageResource(R.drawable.red)
        else iv715.setImageResource(R.drawable.green)

        if (time=="현재시각 : 09시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 17시 월요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 화요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 17시 수요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 목요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 목요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 목요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 목요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 금요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 금요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 금요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 금요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 금요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 금요일") iv717.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 17시 금요일") iv717.setImageResource(R.drawable.red)
        else iv717.setImageResource(R.drawable.green)

        if (time=="현재시각 : 11시 월요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 월요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 화요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 화요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 화요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 수요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 수요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 목요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 목요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 목요일") iv718.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 목요일") iv718.setImageResource(R.drawable.red)
        else iv718.setImageResource(R.drawable.green)

        if (time=="현재시각 : 11시 월요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 월요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 월요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 월요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 화요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 화요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 화요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 목요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 목요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 목요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 목요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 금요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 금요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 13시 금요일") iv719.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 14시 금요일") iv719.setImageResource(R.drawable.red)
        else iv719.setImageResource(R.drawable.green)

        if (time=="현재시각 : 09시 화요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 화요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 화요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 화요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 수요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 수요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 수요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 수요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 09시 목요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 10시 목요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 목요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 목요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 11시 금요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 12시 금요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 15시 금요일") iv720.setImageResource(R.drawable.red)
        else if (time=="현재시각 : 16시 금요일") iv720.setImageResource(R.drawable.red)
        else iv720.setImageResource(R.drawable.green)
    }
}